import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="navbar">
          <div className="nav-title"><img src="/assets/logo.png" /></div>
          <div className="nav-links">
            <span>SELECT DISH</span>
            <span>SELECT DRINK</span>
            <span>ORDER SCREEN</span>
            <span>RECEIPT SCREEN</span>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
